application: fancrawler-drew-test
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /scripts
  static_dir: scripts
- url: /JSON
  static_dir: JSON
  
- url: /getNFLArticles
  script: server.app
  login: admin
- url: /getNHLArticles
  script: server.app
  login: admin
- url: /getNBAArticles
  script: server.app
  login: admin
- url: /getMLBArticles
  script: server.app
  login: admin
  
- url: /getNFLSites
  script: server.app
  login: admin
- url: /getNHLSites
  script: server.app
  login: admin
- url: /getNBASites
  script: server.app
  login: admin
- url: /getMLBSites
  script: server.app
  login: admin
  
- url: /.*
  script: server.app